export const BOOK_APPOINTMENT_REQUEST = 'BOOK_APPOINTMENT_REQUEST'
export const BOOK_APPOINTMENT_SUCCESS = 'BOOK_APPOINTMENT_SUCCESS'
export const BOOK_APPOINTMENT_FAIL = 'BOOK_APPOINTMENT_FAIL'

export const GET_APPOINTMENTS_REQUEST = 'GET_APPOINTMENTS_REQUEST'
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS'
export const GET_APPOINTMENTS_FAIL = 'GET_APPOINTMENTS_FAIL'