export const DOCTOR_LIST_REQUEST = 'DOCTOR_LIST_REQUEST'
export const DOCTOR_LIST_SUCCESS = 'DOCTOR_LIST_SUCCESS'
export const DOCTOR_LIST_FAIL = 'DOCTOR_LIST_FAIL'


export const GET_DOCTOR_DETAILS_REQUEST = 'GET_DOCTOR_DETAILS_REQUEST'
export const GET_DOCTOR_DETAILS_SUCCESS = 'GET_DOCTOR_DETAILS_SUCCESS'
export const GET_DOCTOR_DETAILS_FAIL = 'GET_DOCTOR_DETAILS_FAIL'
